### PR TITLE
Update and fix full auto install and uninstall of Battle.net chocolatey package

### PR DESCRIPTION
**Pull request by Zoullx**
I changed the .gitignore to allow the Battle.net-Setup.exe to be committed because if we download the installer exe we obtain a different sha every time and I use these chocolatey packages with Ansible and it needs the shas to exist and match otherwise the task fails.

I also had to change the way that the uninstaller was being called so that it used the built in chocolatey function in order to get rid of chocolateys prompt about not being able to automatically detect automatic uninstallation.

### CODE REVIEW

**Comment by chtof** [comment]
You want the installer embedded in the Chocolatey package. Have you checked if the installer is redistributable?

**Review by chtof — CHANGES_REQUESTED** [review]
@Zoullx You want the installer embedded in the Chocolatey package. Have you checked if the installer is redistributable?
cf. https://docs.chocolatey.org/en-us/create/create-packages : Sometimes called embedding the binaries, there are functions in the automation scripts you can call that will use the installers directly from the package instead of downloading first. This makes for the most reliable and deterministic packages, but ensure you have the [legal right to distribute](https://docs.chocolatey.org/en-us/information/legal) the software first if publishing to a public location (like the community package repository).

**Comment by chtof** [comment]
@Zoullx Have you read my previous post?

**Comment by Zoullx** [comment]
Sorry, life has been a bit crazy for me lately. I tried looking the redistribution rights but wasn't really able to find anything, however, I recently tried using my internal package setup this way to configure one of my machines with Ansible and it looks like Ansible can't automatically install this package anyway because of the way that Ansible works. So I wouldn't be opposed to removing the exe and the hash stuff so that this package can be published publicly and then I'll personally just use my internal package. Do you want me to add the commit to this PR to remove those things?

**Comment by Zoullx** [comment]
I've updated the gitignore to ignore the Battle.net Setup executable again.

**Comment by chtof** [comment]
You can't generate the checksum on the fly during the installation.
The checksum is to ensure the binary scanned by the antivirus during the Chocolatey review is the same than the one installed.

**Comment by Zoullx** [comment]
Well darn. I guess the only option at that point would be to just not specify the checksum since the executable is built on demand and hence the checksum changes every time. Would you like me to make those changes and submit them to the PR?

**Comment by chtof** [comment]
You can't publish a Chocolatey package for a binary when the checksum changes too often.
Chocolatey packages use checksum to ensure the binary scanned by antivirus is the same binary installed for security reasons.

**Pull request closed without merging**
